export const Type = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_PRODUCT_COMPLETELY:"REMOVE_PRODUCT_COMPLETELY",
  EMPTY_CART:"EMPTY_CART",
  SET_USER:"SET_USER"
};